### ISSUE TITLE
No player named 'xxxxxx' is currently playing.

### ISSUE THREAD

**Issue by Morindra** [Rythal/Carbonite#183]
Once someone leaves the party, I am getting this message spammed until I /reload.

**Comment by samyonair** [comment]
Have reopend it, have seen the bug is mentioned in more addons, some have found workarounds and if it is blizzbug problem is users will blame us for as mentioned in Forum, has to do with updatelist have found 532 Threads on euGB Forums, evantually it would be better to find a fix

**Comment by IrcDirk** [comment]
How to recreate this?

**Comment by DaveJ61** [comment]
I have seen it when a guild member logs off... Others have seen it when someone leaves a group/party...

**Comment by IrcDirk** [comment]
Hard for me to reproduce so i can debug it :/ But its related to FRIENDLIST_UPDATE event, as its bugged and not allways fires as users logout...

**Comment by IrcDirk** [comment]
Ok i think i found fix for this:

https://github.com/Rythal/Carbonite/pull/229

Now everyone who have this issue download latest version from GitHub and test this.

**Comment by atk** [comment]
I have already merged the fix (it seemed harmless enough), so you can just pull the current version.

**Comment by Morindra** [comment]
Updated Carbonite after above comment and it did not resolve issue.  Interesting note; We were talking about this in my raid group and someone said that it might be Recount.  I switched from Recount to Skada and it seemed to stop.  I will let the group know if it returns after this weekend's raiding.

**Comment by Ghosthree3** [comment]
I also had someone tell me it was Recount. However it happens to me when friends log off that were never in my party so I don't know how Recount could even come into play.

**Comment by IrcDirk** [comment]
This is becouse of Blizz bug and it affects many addons, so fixing it in Carbonite may not resolve problem of other addons.

**Comment by samyonair** [comment]
fixed in carbonite -- closed
