### ISSUE TITLE
Warehouse Module Broken in German

### ISSUE THREAD

**Issue by samyonair** [Rythal/Carbonite#318]
See Forum 
http://www.wowinterface.com/forums/showthread.php?t=51746

to figure out failueres tried

eng file for german (copied locally eng file over german changed to deDE with language spezific head)
getting integer error

if I juse file in repo get a nil 
If set true after deDE, true, true) integer error

From Translators would be helpful if it is a german problem or other languages have same problems

error and try is not working

cannot figure out why this problems happen

**Comment by samyonair** [comment]
failure themes to be in L["ItemTypes"]

I for now have no Idea how to fix it

**Comment by atk** [comment]
"Reagent" = "Zutat" is missing. I have already pushed a fix.

**Comment by samyonair** [comment]
reopen it

it is missing for fr, es usw although

then this would missing in other language files same way

but with your fix 

Date: 2015-06-16 00:48:48
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite\NxUI.lua line 3544:
   attempt to index field '?' (a nil value)
Debug:
   [C]: ?
   Carbonite\NxUI.lua:3544: SetType()
   Carbonite\NxUI.lua:5755: Update()
   Carbonite.Warehouse\NxWarehouse.lua:1774: Update()
   Carbonite.Warehouse\NxWarehouse.lua:1199: Create()
   Carbonite.Warehouse\NxWarehouse.lua:1349: ToggleShow()
   Carbonite.Warehouse\NxWarehouse.lua:691: Func()
   Carbonite\NxUI.lua:4914:
      Carbonite\NxUI.lua:4884
Locals:

AddOns:
  Swatter, v5.21d.5538 (SanctimoniousSwamprat)
  Accountant, v6.01.60100
  AddOnSkins, v3.16
  Atlas, v1.31.01
  AtlasLoot, vv8.00.00_2
  AuctionMaster, v6.0.1
  Babylonian, v5.1.DEV.332(/embedded)
  BrokerLDB, v2.01
  BuyMaxStack, v1.06
  Carbonite, v6.2.0
  CarboniteInfo, v6.2.0
  CarboniteNotes, v6.2.0
  CarboniteQuests, v6.2.0
  CarboniteSocial, v6.2.0
  CarboniteWarehouse, v6.2.0
  CarboniteWeekly, v6.2.0
  Clique, vv60100-1.0.0
  Configator, v5.1.DEV.376(/embedded)
  DBMCore, v
  DBMDefaultSkin, v
  DBMGarrisonInvasions, v
  DBMLDB, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Decursive, v2.7.4.2
  ElvUI, v8.11
  ElvUIAutoLog, v1.16
  ElvUIBagFilter, v1.4
  ElvUIChannelAlerts, v3.07
  ElvUIChatTweaks, v7.03
  ElvUIChatTweaksExtra, v
  ElvUICustomTweaks, v1.18
  ElvUIEnhanced, v3.1.0-beta3
  ElvUIExtraActionBars, v2.25
  ElvUILocPlus, v2.07
  ELvUILootOptions, v6.0.3b
  ElvUIProfessions, v1.8
  ElvUIRaidMarkers, v4.24
  elvuireminder, v1.17
  ElvUIVisualAuraTimers, v1.45
  Enchantrix, v5.21d.5538 (SanctimoniousSwamprat)
  EnchantrixBarker, v5.21d.5538 (SanctimoniousSwamprat)
  GatherMate2, v1.33.5
  GTFO, v4.36.1
  HandyNotes, vv1.3.3
  HandyNotesDraenorTreasures, v1.12
  LibExtraTip, v5.12.DEV.363(/embedded)
  MasterPlanA, v
  MizusRaidTracker, vv0.63.1
  Omen, v3.1.10
  OregorgerTracker, vv1.3
  Outfitter, v5.10b10
  Pawn, v1.9.16
  PawnCons, v1.05
  Postal, v3.5.4
  RaidachievmentsAFKModuleElvUI, v1.01
  SimpleRareElite, v1.25
  Skada, v1.4-30
  Skillet, v2.81
  SlideBar, v5.21d.5538 (SanctimoniousSwamprat)
  Stubby, v5.21d.5538 (SanctimoniousSwamprat)
  ThogarHelper, v1.50
  TipHelper, v5.12.DEV.351(/embedded)
  VuhDo, v3.67
  VuhDoOptions, v3.67
  BlizRuntimeLib_deDE v6.1.2.60100 <none>
  (ck=6e5)

same problem will clear my cache and try

**Comment by samyonair** [comment]
cleared cache problem still there will reproduce tommorow without addons on clean install

**Comment by atk** [comment]
I'll have a look into it later.

**Comment by atk** [comment]
Have you tried DEV or master? My fix was in DEV.

**Comment by samyonair** [comment]
I Only use DEV because working on DEV cannot test it on clean Version before weekend to many things to do for work

**Comment by atk** [comment]
OK, back to testing...

**Comment by atk** [comment]
I believe I have found the error; The button is initialized on line 1583, 1642, ... with the type "Lager" instead of "Warehouse", which shouldn't be translated in the first place, since it is a control string, not an output. I have undone the faulty translations and will test again before committing.

**Comment by atk** [comment]
Now the issue is really resolved.
